USER = "admin"
PASS = "wamp321"
SECRET_KEY = "wampjwtkey"
CC_ENCRYPT_KEY = "wampcreditcardkey"
DB_URI = f"mongodb+srv://{USER}:{PASS}@cluster0.kiguh.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
